### ISSUE TITLE
Additional model metadata

### ISSUE THREAD

**Issue by WilliamKarolDiCioccio** [WilliamKarolDiCioccio/open_local_ui#12]
We need to write a JSON file containing additional metadata for Ollama models. Helpful information as if the model is multimodal cannot directly be retrieved using Ollama API as far as I know, that means we would have to deal with model families making things much more complex. Knowing if the model is multimodal would enable us to conditionally allow to add images as message attachments therefore reducing user confusion. Other less important infos I would like to add are: model creator, number of push and pulls of the model

**Comment by Rossi1337** [comment]
We could fetch additional information from the ollama homepage.
The search API is producing a list of models it looks like this https://ollama.com/library?q=searchterm
Unfortunately that produces html which we would have to parse. There is no json search API.

For each model there is a own page like this one
https://ollama.com/library/llama3:70b
with a standardized section/table which contains additional model metdata. Unfortunately also that page does not list if a model is mulitmodal or what features it supports. That is only mentioned in the descriptive text.

**Comment by WilliamKarolDiCioccio** [comment]
Yes, I asked that yesterday on the ollama Discord server and they confirmed this. However I still wonder how the ollama executable checks whether a model exists or not if there is no library API

**Comment by WilliamKarolDiCioccio** [comment]
There are updates on the topic. See [here](https://discord.com/channels/1128867683291627614/1246129813635203092/1246132306754932826) on Discord
