### ISSUE TITLE
Adapt App ID and "com.example.open_local_ui" 

### ISSUE THREAD

**Issue by Rossi1337** [WilliamKarolDiCioccio/open_local_ui#14]
Just found out the settings of the App are stored in

C:\Users\username\AppData\Roaming\com.example\open_local_ui

This comes from the inital project setup. It would be better to replace this with something more meaningfull.

**Comment by Rossi1337** [comment]
Just did a quick text search and these are the places that would need to be adapted:

open_local_ui\open_local_ui\linux\CMakeLists.txt
  10,21: set(APPLICATION_ID "com.example.open_local_ui")

open_local_ui\open_local_ui\macos\Runner\Configs\AppInfo.xcconfig
  11,29: PRODUCT_BUNDLE_IDENTIFIER = com.example.openLocalUi
  14,38: PRODUCT_COPYRIGHT = Copyright © 2024 com.example. All rights reserved.

open_local_ui\open_local_ui\macos\Runner.xcodeproj\project.pbxproj
  388,33: 				PRODUCT_BUNDLE_IDENTIFIER = com.example.openLocalUi.RunnerTests;
  402,33: 				PRODUCT_BUNDLE_IDENTIFIER = com.example.openLocalUi.RunnerTests;
  416,33: 				PRODUCT_BUNDLE_IDENTIFIER = com.example.openLocalUi.RunnerTests;

open_local_ui\open_local_ui\windows\runner\Runner.rc
  92,35:             VALUE "CompanyName", "com.example" "\0"
  96,57:             VALUE "LegalCopyright", "Copyright (C) 2024 com.example. All rights reserved." "\0"

**Comment by WilliamKarolDiCioccio** [comment]
Can I assign that to you? I'm working on the TTS feature

**Comment by Rossi1337** [comment]
See pull request #15
