### ISSUE TITLE
Selection across different widgets

### ISSUE THREAD

**Issue by WilliamKarolDiCioccio** [WilliamKarolDiCioccio/open_local_ui#22]
We need to enable text selection across multiple widgets otherwise users have to copy code and normal text separately

**Comment by Rossi1337** [comment]
I did only a quick research but maybe it it would be an option to switch to a different markdown package?
This one looks very promising: [markdown_widget](https://pub.dev/packages/markdown_widget)

Will not have much time to test this further for now but wanted to drop this here.

**Comment by Rossi1337** [comment]
As a starting point to try this out see #30

**Comment by WilliamKarolDiCioccio** [comment]
I've applied the necessary changes in #30 and merged with main. Closing this as completed. Forgot to do it in the commit. I definitely need to stick a post-it to the screen
