### ISSUE TITLE
Check in generated code to make building easier for starters

### ISSUE THREAD

**Issue by Rossi1337** [WilliamKarolDiCioccio/open_local_ui#32]
Hi,
I open this for further discussion. When I checkout now the code it is no longer easy to build it.
Basically what I have to do today is run some different code generators and other tools before I can build the App.

- I need to create an .env file and populate it with some variables that I have to find out from the code.
- Run build_runner
- Then need to run somewhere the generator for the protobufs
- Need to findle around with some python building to generate the server part

To make things a little bit easier I would suggest to at least check in 
open_local_ui/services/protobufs/server.pbgrpc.dart

I do not have the protobuf compiler installed so I cannot generate this code easily. I assume this code will change only very rarely so I would suggest to check it in.

For the .env I do not have a good solution but I would suggest to check in a *.env.test* with the following content:

GITHUB_FEEDBACK_PAT=
GITHUB_COLLABORATORS_PAT=
SUPABASE_URL=
SUPABASE_ANON_KEY=

So you can just copy that one and put it into *.env* to get started. 

This would make checking out and building much easier.

**Comment by WilliamKarolDiCioccio** [comment]
Wilco! Taking care of it tomorrow

**Comment by WilliamKarolDiCioccio** [comment]
Meanwhile i checked out the gRPC generated files. Tommorow I'll add development and testing environment variables and close the issue

**Comment by WilliamKarolDiCioccio** [comment]
@Rossi1337 are you satisfied with the update? 
We might also add a setup task to automatically generate all the code the first time.
Hope it makes things easier also for new contributors

**Comment by Rossi1337** [comment]
Yes it is super smooth now. At least if you have some basic experience with Flutter.
Checkout code. Add the .env file. Then in pubspec.yaml click once "Get Packages" and your are done and ready to launch the App.
I don't think a setup task is necessary.
