### ISSUE TITLE
Automatic language detection does not update the settings drop down box

### ISSUE THREAD

**Issue by Rossi1337** [WilliamKarolDiCioccio/open_local_ui#39]
When you launch the App it now correctly detects the system language based on the system locale.
In my case German. But when I go to the settings page it displays "English" (I assume that is the default)
Also as soon as I select there a different language I can no more go back to "automatic detection".
We need to add to the drop down box an additional entry "System". 
That one should be the new default value and when it is selected it clear the language in the settings file again.

**Comment by WilliamKarolDiCioccio** [comment]
I see the problem. My fault, didn't test it on my machine (lazy). Would you mind handling it?

**Comment by Rossi1337** [comment]
Yes I will look into this

**Comment by Rossi1337** [comment]
Will work on this one today. Got it already finished but lost all changes due to my stupidity. Need to do it again ;-)

**Comment by WilliamKarolDiCioccio** [comment]
Don't tell this to me, don't know how many times I've lost my changes. Those are the risks of the profession :(
