### ISSUE TITLE
Review translations for release 0.2

### ISSUE THREAD

**Issue by WilliamKarolDiCioccio** [WilliamKarolDiCioccio/open_local_ui#47]
I'll let Ollama figure out the translations and then ask for a review on some forum

**Comment by Rossi1337** [comment]
Sure I can do that. Just let me know once you have regenerated the files.

**Comment by WilliamKarolDiCioccio** [comment]
Of course, thank you so much

**Comment by WilliamKarolDiCioccio** [comment]
@Rossi1337  I've just committed the new translations. Take your time to review the German ones, I'll do the same for Italian

**Comment by Rossi1337** [comment]
I review them today.

Just checked out. @WilliamKarolDiCioccio please note that there is currently a compile error when I check out.
**create_folder.dart** is missing in the repo!
