### ISSUE TITLE
Add a Icon to the App

### ISSUE THREAD

**Issue by Rossi1337** [WilliamKarolDiCioccio/open_local_ui#5]
Instead of the default Flutter Icon a own icon would be nice.

**Comment by WilliamKarolDiCioccio** [comment]
Actually I wasn't able to think to any logo. I'm labeling this as help wanted and good first issue so maybe newcomers with more design experience will be engaged

**Comment by WilliamKarolDiCioccio** [comment]
I was thinking to have a more detailed discussion of our ideas [here](https://github.com/WilliamKarolDiCioccio/open_local_ui/discussions/35) and then maybe I'll find someone on Fiverr to get a more professional result.

**Comment by WilliamKarolDiCioccio** [comment]
Closing after #7e2e7f2feaaa341801089db24126a857d119de23
