### ISSUE TITLE
Rework the "Scroll down" button

### ISSUE THREAD

**Issue by Rossi1337** [WilliamKarolDiCioccio/open_local_ui#53]
The "scroll down" button in the chat window is currently located on the left side and is quite big. It is exactly there where new text is generated. I try to read new text when "generation" is ongoing. This button on top of it is disturbing this.

I would suggest to move that button somewhere else. Maybe just push it to the right side and maybe make it more compact (remove the text and only keep the icon)?

Open for discussion.

**Comment by Rossi1337** [comment]
Also relatred to that button is #46

**Comment by WilliamKarolDiCioccio** [comment]
We might leave just the icon as you said with a semi-transparent circle as background. The most straightforward place to move it to is the center but it is a bit difficult as I'm using the overlay widget and so there's no easy way to do it. I browse pub for a tailored solution.

Let me seize the opportunity to tell you this week I won't be really active as I finished high school and I'm studying for the exam

**Comment by WilliamKarolDiCioccio** [comment]
@Rossi1337 What do you think of this? It is centered and has a slightly transparent background that allows to easily read what's behind it. I highlighted it in the screenshot

![Screenshot 2024-06-16 114711](https://github.com/WilliamKarolDiCioccio/open_local_ui/assets/88447902/8082a87a-9df3-4f84-bbef-b48a5a8b4125)

**Comment by Rossi1337** [comment]
This looks really cool. I think this will work quite well.

**Comment by Rossi1337** [comment]
Good luck for your exams!!!
I don't want to see you that much on github then ;-)
