### ISSUE TITLE
Suggestion for UI change. Remove the "Home" section

### ISSUE THREAD

**Issue by Rossi1337** [WilliamKarolDiCioccio/open_local_ui#9]
When you open the App you end up on the "Home" section. There you have 2 big buttons leading you to github.
This is quite useless for most of the users. I would suggest the following UI change. 
When you open the App show directly the "Chat" section. So the user can straight away start to chat. This is what I want to do when the App opens.
Remove the "Home" section completely and move the two buttons from there into the "About" section.

**Comment by WilliamKarolDiCioccio** [comment]
I've just deleted the home page and moved its content to the about page. Moreover I had a little fun with the GitHub API, now all contributors will get a mention in the app. I hope to foster community engagement. Here's a picture of my build so you can see the result as a GitHub PAT is need to query repository contributors. Closing this issue.

![Screenshot 2024-05-29 222838](https://github.com/WilliamKarolDiCioccio/open_local_ui/assets/88447902/8582383c-6fc0-4c14-8225-31e5665e8aa8)

**Comment by Rossi1337** [comment]
Thats really nice but now I have to update my avatar icon to something cooler ;-)
